version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      types:
        patterns: ['@types/*']
      dev-dependencies:
        dependency-type: 'development'

  - package-ecosystem: 'npm'
    directory: '/dashboard'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
