import { ethers, JsonRpcProvider, Wallet, Contract } from 'ethers';
import { config } from '../config';
import { logger } from './logger';
import { BlockchainInfo } from '../types';

// DIDRegistry ABI — matches contracts/DIDRegistry.sol
const DID_REGISTRY_ABI = [
  'function owner() view returns (address)',
  'function identityCount() view returns (uint256)',
  'function registerIdentity(bytes32 biometricIDHash, string did) external',
  'function verifyIdentity(bytes32 biometricIDHash) view returns (string)',
  'function isRegistered(bytes32 biometricIDHash) view returns (bool)',
  'function revokeIdentity(bytes32 biometricIDHash) external',
  'function transferOwnership(address newOwner) external',
  'event IdentityRegistered(bytes32 indexed biometricIDHash, string did, uint256 timestamp)',
  'event IdentityRevoked(bytes32 indexed biometricIDHash, uint256 timestamp)',
];

// Groth16Verifier ABI — generated by snarkjs
const VERIFIER_ABI = [
  'function verifyProof(uint[2] _pA, uint[2][2] _pB, uint[2] _pC, uint[3] _pubSignals) view returns (bool)',
];

let provider: JsonRpcProvider | null = null;
let wallet: Wallet | null = null;
let didRegistryContract: Contract | null = null;
let verifierContract: Contract | null = null;

const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 1000;

async function withRetry<T>(fn: () => Promise<T>, label: string): Promise<T> {
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      return await fn();
    } catch (err) {
      logger.warn(`${label}: attempt ${attempt}/${MAX_RETRIES} failed`, {
        error: (err as Error).message,
      });
      if (attempt === MAX_RETRIES) throw err;
      await new Promise((r) => setTimeout(r, RETRY_DELAY_MS * attempt));
    }
  }
  throw new Error(`${label}: all retries exhausted`);
}

/**
 * Wire up the optional blockchain layer. ADR 0017 — this service is
 * BEST-EFFORT. Missing env vars (no private key, no RPC URL, no
 * registry/verifier addresses) leave the service in "unavailable"
 * mode; the platform boots cleanly and tenants whose
 * `did_provider='off-chain'` (the default) never notice. Tenants who
 * opted into a chain provider see their `registerIdentityOnChain`
 * calls reject with "DIDRegistry contract not initialized" — that's
 * the contract; misconfigured opt-in is the operator's problem.
 *
 * This function MUST NOT throw and MUST NOT call `process.exit`. The
 * caller in `src/server.ts` already wraps it in a try/catch and warns,
 * but the inner guards here mean a network blip on `getNetwork()`
 * doesn't even bubble up to that handler — the platform stays in a
 * known partially-degraded mode.
 */
export async function initBlockchain(): Promise<void> {
  if (!config.blockchain.privateKey) {
    logger.warn('Blockchain: No private key configured — blockchain features disabled (ADR 0017 default)');
    return;
  }

  try {
    provider = new JsonRpcProvider(config.blockchain.rpcUrl);
    wallet = new Wallet(config.blockchain.privateKey, provider);
  } catch (err) {
    logger.warn('Blockchain: provider/wallet construction failed — features disabled', {
      error: (err as Error).message,
    });
    provider = null;
    wallet = null;
    return;
  }

  // Best-effort network probe. An RPC outage at boot must NOT abort
  // the server; we log and leave `provider` populated so a later call
  // can still try (the JsonRpcProvider is lazy and will reconnect).
  try {
    const network = await provider.getNetwork();
    logger.info(`Blockchain: Connected to ${network.name} (chainId: ${network.chainId})`);
    logger.info(`Blockchain: Deployer address: ${wallet.address}`);
  } catch (err) {
    logger.warn('Blockchain: RPC network probe failed — proceeding in degraded mode', {
      error: (err as Error).message,
      rpcUrl: config.blockchain.rpcUrl,
    });
  }

  if (config.blockchain.didRegistryAddress) {
    try {
      didRegistryContract = new Contract(
        config.blockchain.didRegistryAddress,
        DID_REGISTRY_ABI,
        wallet,
      );
      logger.info(`Blockchain: DIDRegistry at ${config.blockchain.didRegistryAddress}`);
    } catch (err) {
      logger.warn('Blockchain: DIDRegistry contract bind failed', {
        error: (err as Error).message,
      });
      didRegistryContract = null;
    }
  } else {
    logger.info('Blockchain: DIDRegistry address not configured — on-chain DID registration unavailable');
  }

  if (config.blockchain.verifierAddress) {
    try {
      verifierContract = new Contract(
        config.blockchain.verifierAddress,
        VERIFIER_ABI,
        wallet,
      );
      logger.info(`Blockchain: Verifier at ${config.blockchain.verifierAddress}`);
    } catch (err) {
      logger.warn('Blockchain: Verifier contract bind failed', {
        error: (err as Error).message,
      });
      verifierContract = null;
    }
  } else {
    logger.info('Blockchain: Verifier address not configured — on-chain proof verification unavailable');
  }
}

export async function registerIdentityOnChain(
  biometricIDHash: string,
  did: string,
): Promise<{ txHash: string; blockNumber: number }> {
  if (!didRegistryContract) {
    throw new Error('DIDRegistry contract not initialized');
  }

  return withRetry(async () => {
    const tx = await didRegistryContract!.registerIdentity(biometricIDHash, did);
    const receipt = await tx.wait();
    logger.info('Blockchain: Identity registered', {
      txHash: receipt.hash,
      blockNumber: receipt.blockNumber,
    });
    return { txHash: receipt.hash, blockNumber: receipt.blockNumber };
  }, 'registerIdentityOnChain');
}

export async function verifyProofOnChain(
  pA: [string, string],
  pB: [[string, string], [string, string]],
  pC: [string, string],
  pubSignals: [string, string, string],
): Promise<boolean> {
  if (!verifierContract) {
    throw new Error('Verifier contract not initialized');
  }

  return withRetry(async () => {
    return await verifierContract!.verifyProof(pA, pB, pC, pubSignals);
  }, 'verifyProofOnChain');
}

async function getIdentityCount(): Promise<number> {
  if (!didRegistryContract) return 0;
  try {
    const count = await didRegistryContract.identityCount();
    return Number(count);
  } catch {
    return 0;
  }
}

export async function getBlockchainInfo(): Promise<BlockchainInfo> {
  const latestBlock = provider ? await provider.getBlockNumber() : 0;
  const identityCount = await getIdentityCount();

  return {
    network: 'Base Sepolia',
    chainId: config.blockchain.chainId,
    rpcUrl: config.blockchain.rpcUrl,
    contracts: {
      DIDRegistry: config.blockchain.didRegistryAddress || 'not deployed',
      Verifier: config.blockchain.verifierAddress || 'not deployed',
    },
    identityCount,
    latestBlock,
    deployerAddress: wallet?.address ?? 'not configured',
  };
}

export function isBlockchainReady(): boolean {
  return provider !== null && wallet !== null;
}

export function getProvider(): JsonRpcProvider | null {
  return provider;
}
