package dev.zeroauth.android

import android.app.Application
import timber.log.Timber

/**
 * Application entry point. Lives long enough to host process-wide
 * singletons (logging, Retrofit client, KeystoreManager) once those
 * land in the prover-glue sprint task.
 *
 * Today the only responsibility is wiring Timber in debug builds. The
 * release variant intentionally has NO logging because the only thing
 * we'd want to log around the prover path is highly sensitive (biometric
 * commitments, session nonces, proof bytes). The phone is supposed to
 * be a sealed black box from the operator's perspective; debugging
 * happens in the dashboard/console, not on-device.
 *
 * NB: BuildConfig.DEBUG is generated by AGP from buildTypes — see
 * app/build.gradle.kts.
 */
class ZeroAuthApp : Application() {

    override fun onCreate() {
        super.onCreate()
        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
            Timber.tag(TAG).d("ZeroAuthApp.onCreate (debug build)")
        }
        // TODO(prover-glue): initialise KeystoreManager here so the
        // BiometricGate can resolve the user's stored credential before
        // the first composable mounts.
    }

    companion object {
        private const val TAG = "ZeroAuthApp"
    }
}
